version: '3.8'
services:
  app:
    container_name: app
    build: ./Docker/php
    volumes:
      - .:/var/www
    environment:
      - TZ=Asia/Tokyo
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:8.0
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./Docker/db/my.cnf:/etc/mysql/conf.d
      - ./Docker/db/init:/docker-entrypoint-initdb.d
      - ./Docker/db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: PBA
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
    tty: true
