version: '3.8'
services:
  app:
    container_name: app
    build: ./Docker/php
    volumes:
      - .:/var/www
    environment:
      - TZ=Asia/Tokyo
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 8080:443
    volumes:
      - ./laravel-project:/var/www/laravel-project
      - ./Docker/nginx/conf.d:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    working_dir: /var/www
    depends_on:
      - app
  certbot:
    image: certbot/certbot:v1.7.0
    container_name: certbot
    # build: ./Docker/certbot
    # 10日おきに証明書を更新する(期限切れまで30日以上あれば更新しない)
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"
    volumes:
      - ./letsencrypt:/etc/letsencrypt #こちらに取得したssl証明書が配置されます。nginxコンテナでも同じくマウントして共有します。
      - ./laravel-project:/var/www/laravel-project
    command: ["--version"]
  db:
    image: mysql:8.0
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./Docker/db/my.cnf:/etc/mysql/conf.d
      - ./Docker/db/init:/docker-entrypoint-initdb.d
      - ./Docker/db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: PBA
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
    tty: true
